---
layout: post
title: java31
sitemap: false
hide_last_modified: true
---
# 예외처리

* toc
{:toc .large-only}

# 예외처리
자바에서 처리하는 모든 예외는 `Throwable` 하위의 `Exception` 클래스에 종속된다. `Throwable` 하위에는 `Error` 클래스도 있는데, 이는 JVM. 즉, 시스템 레벨에서 발생하는 오류로써 개발자가 처리 할 수 없다.

# Exception

## Unchecked Exception

런타임 시 체크 되는 예외로써, 논리적 오류에 의해 발생하는 경우가 많다. 모든 Unchecked Exception은 `RuntimeException` 을 상속 받는다.
예: `IOException`, `SQLException`, `ClassNotFoundException`

`RuntimeException`은  try-catch나 throws를 이용한 예외 처리가 강제 되지 않는다. 즉, 예외 처리를 해주지 않아도 프로그램 실행 시 컴파일 오류가 발생하지 않는다.

발생 한 예외는 처리 될 때까지 상위 메서드로 전파되며, 최상위까지 처리되지 않은 `RuntimeException` 은 프로그램을 종료 시킨다.

## Checked Exception

컴파일 시 체크하는 예외이다. 컴파일러가 개발자가 해당 예외를 반드시 처리하도록 강제한다.

`RuntimeException` 을 상속 받지 않는 Exception은 모두 `checked Exception` 이다.

보통 파일 입출력, 네트워크 통신 등 **외부 환경**과의 상호작용 시 발생할 가능성이 높다
예: `NullPointerException`, `ArrayIndexOutOfBoundsException`, `ArithmeticException`

`CheckedException`은 컴파일러가 예외 처리를 강제하기 때문에, 해당 메서드 내에서 예외를 처리 하거나(throw), 상위 메서드로 예외를 위임(throws)해야 한다. 이 처리가 되지 않을 시 컴파일 오류가 발생된다.

여기서 상위 메서드란 해당 메서드를 호출한 메서드를 뜻한다.

throws로 예외를 던진 후 최상위 메서드까지 처리가 안되면 JVM에서 이를 처리한다(비정상 종료)

## 비교

|  | checked Exception | unchecked Exception |
| --- | --- | --- |
| 발생 시점 | 컴파일 시 | 런타임 시 |
| 발생 원인 | 외부 환경에서 발생할 수 있는 예측 가능한 문제 | 프로그래밍 오류나 논리적 실수 |
| 처리 | throws나 try-catch로 반드시 처리해주어야 하며, 실행하지 않을 시 컴파일 에러 발생 | 처리가 없어도 실행은 됨 |

`RuntimeException` 는 try-catch나 throws의 여부와 상관 없이 우선 프로그램이 실행되고, `CheckedException` 은 try-catch나 throws가 있어야만 프로그램이 실행된다.

# 처리

## throw

예외를 그 즉시 발생시킨다.

```java
public void register(String id, String pw, String email){
    if(passwordChecker.checkPasswordWeak(pw)) {
        throw new WeakPasswordException();
    }
    // 생략
}
```

## throws

해당 메서드에서 예외 발생 시, 이를 상위 호출자에게 전달한다. 

상위 호출자란, 해당 메서드를 호출한 메서드를 뜻한다

```java
public void readFile() throws IOException {
    FileReader file = new FileReader("test.txt");  // 파일이 없을 경우 FileNotFoundException 발생
    BufferedReader fileInput = new BufferedReader(file);
    System.out.println(fileInput.readLine());  // 읽는 중에 문제가 발생하면 IOException 발생
}
```

```java
public void process() {
    try {
        readFile();  // readFile()에서 IOException 발생 가능
    } catch (IOException e) {
        System.out.println("Error occurred: " + e.getMessage());  // 예외 처리
    }
}
```

```java
public static void main(String[] args) {
    new Main().process();
}
```

## try-catch

예외가 발생할 수 있는 코드를 `try` 안에 작성하고, `catch` 에서 이를 처리한다. 

### finally

try-catch와 함께 쓰이며, 예외가 발생 하든 안 하든 항상 실행된다.

## Custom Exception

**사용자 정의 예외**는 사용자가 예외명을 직접 정의함으로써 예외가 발생한 원인이나 의미를 명확하게 파악 할 수 있게 해준다.

```java
throw new InvalidUserInputException("The user input is invalid");
```

또한, 예외마다 다른 후처리가 필요 할 때 이를 지원해준다.

이는 catch문에서, 혹은 Custom Exception class 내부에서 모두 가능하다. 

Java에서 기본적으로 제공하는 Exception 들은 내부 메서드 변경이 불가능하므로 catch문으로 밖에 후처리가 되지 않는다.